package com.ssh.pojo;
// Generated 2019-12-26 16:04:58 by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clazz generated by hbm2java
 */
public class Clazz implements java.io.Serializable {

	private int cid;
	private Jieduan jieduan;
	private String cname;
	private String type;
	private String bzr;
	private String ls;
	private Set rols = new HashSet(0);
	private Set students = new HashSet(0);

	public Clazz() {
	}

	public Clazz(int cid) {
		this.cid = cid;
	}

	public Clazz(int cid, Jieduan jieduan, String cname, String type, String bzr, String ls, Set rols, Set students) {
		this.cid = cid;
		this.jieduan = jieduan;
		this.cname = cname;
		this.type = type;
		this.bzr = bzr;
		this.ls = ls;
		this.rols = rols;
		this.students = students;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public Jieduan getJieduan() {
		return this.jieduan;
	}

	public void setJieduan(Jieduan jieduan) {
		this.jieduan = jieduan;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getBzr() {
		return this.bzr;
	}

	public void setBzr(String bzr) {
		this.bzr = bzr;
	}

	public String getLs() {
		return this.ls;
	}

	public void setLs(String ls) {
		this.ls = ls;
	}

	public Set getRols() {
		return this.rols;
	}

	public void setRols(Set rols) {
		this.rols = rols;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

	@Override
	public String toString() {
		return "Clazz [cid=" + cid + ", jieduan=" + jieduan + ", cname=" + cname + ", type=" + type + ", bzr=" + bzr
				+ ", ls=" + ls + "]";
	}
	
	
}
