package com.ssh.pojo;
// Generated 2019-12-20 16:46:13 by Hibernate Tools 5.4.7.Final

/**
 * User generated by hbm2java
 */
@SuppressWarnings("all")
public class User implements java.io.Serializable {

	private int uid;
	private Integer sid;
	private Integer rid;
	private String uname;
	private String upwd;

	public User() {
	}

	public User(int uid) {
		this.uid = uid;
	}

	public User(int uid, Integer sid, Integer rid, String uname, String upwd) {
		this.uid = uid;
		this.sid = sid;
		this.rid = rid;
		this.uname = uname;
		this.upwd = upwd;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	@Override
	public String toString() {
		return "User [uid=" + uid + ", sid=" + sid + ", rid=" + rid + ", uname=" + uname + ", upwd=" + upwd + "]";
	}
	
	

}
